# USER API ================================================================

@host=localhost:8080

### TODOS OS USUÁRIOS
GET /api/v1/users HTTP/1.1
Host: localhost:8080
Accept: application/json


### Get all users
# @name= getAllUsers

GET /api/v1/users HTTP/1.1
Host: {{host}}
Accept: application/json

### Create a new valid User
# @name = createNewUser

POST /api/v1/users HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "email": "batata@gmail.com",
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Create a new valid User
# @name = createNewUser

POST /api/v1/users HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "email": "tomate@gmail.com",
    "password": "1234RT56",
    "handle": "tomate",
    "name": "Tomate",
    "roles": [
        "ROLE_USER"
    ],
    "company": "tomate inc"
}



### Try and create an invalid User
# @name = tryCreateInvalidUser

POST /api/v1/users HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "email": "batata@potato.com",
    "password": "1234",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Create a new valid Ticket
# @name = createNewTicket

POST /api/v1/tickets HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_solicitante": 2,
    "id_destinatario": 1,
    "acao": "Manutenção",
    "detalhes": "Detalhes do ticket",
    "equipamento": "Equipamento do ticket",
    "observadores": ["batata@gmail.com", "adriana@gmail.com"]
}

### Create a new valid Ticket
# @name = createNewTicket

POST /api/v1/tickets HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_solicitante": 2,
    "id_destinatario": 1,
    "acao": "Manutenção",
    "detalhes": "CPU não liga",
    "equipamento": "CPU",
    "observadores": ["adriana@gmail.com"]
}

### Create a new valid Ticket
# @name = createNewTicket

POST /api/v1/tickets HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_solicitante": 1,
    "detalhes": "Detalhes do ticket",
    "acao": "Manutenção",
    "equipamento": "Equipamento do ticket",
    "observadores": ["batata@gmail.com", "adriana@gmail.com"]
}


### Get all tickets
# @name= getAllTickets

GET /api/v1/tickets HTTP/1.1
Host: {{host}}
Accept: application/json


### Update a valid Ticket
# @name = updateNewTicket

PATCH /api/v1/tickets/1 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_responsavel": 2,
    "status": "CANCELADO",
    "motivo": "Falta detalhes para realizar o serviço"
}

### Update a valid Ticket
# @name = updateNewTicket

PATCH /api/v1/tickets/2 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_responsavel": 2,
    "status": "CONCLUIDO"
}


### Update a invalid Ticket
# @name = updateNewTicket

PATCH /api/v1/tickets/3 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_responsavel": 2,
    "status": "PENDENTE"
}


### Delete a Ticket
# @name = deleteNewTicket

DELETE /api/v1/tickets/3 HTTP/1.1
Host: {{host}}

### Update a deleted Ticket
# @name = updateNewTicket

PATCH /api/v1/tickets/3 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "id_responsavel": 2,
    "status": "CONCLUIDO"
}
